apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  releaseName: node-exporter
  chart:
    spec:
      chart: prometheus-node-exporter
      version: "4.31.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 60m
