apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../manifests/zalando-pgo
  - ../manifests/ingress-nginx-helm-repo # this only installs the helm repo, to allow multipe installation of ingress-nginx
