apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  releaseName: nginx
  chart:
    spec:
      chart: ingress-nginx
      version: "4.9.1"
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
  interval: 60m
