apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  releaseName: linkerd-crds
  chart:
    spec:
      chart: linkerd-crds
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
  interval: 60m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  releaseName: linkerd-control-plane
  chart:
    spec:
      chart: linkerd-control-plane
      version: "1.16.11"
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
  interval: 60m
  dependsOn:
    - name: linkerd-crds
