kind: Namespace
apiVersion: v1
metadata:
  name: kube-system
  annotations:
    linkerd.io/inject: disabled
  labels:
    config.linkerd.io/admission-webhooks: disabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: linkerd
  namespace: linkerd
spec:
  interval: 60m
  url: https://helm.linkerd.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  releaseName: linkerd-crds
  chart:
    spec:
      chart: linkerd-crds
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
  interval: 60m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  releaseName: linkerd-control-plane
  chart:
    spec:
      chart: linkerd-control-plane
      version: "1.16.11"
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
  interval: 60m
  dependsOn:
    - name: linkerd-crds
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: linkerd-viz
spec:
  releaseName: linkerd-viz
  chart:
    spec:
      chart: linkerd-viz
      version: "30.12.11"
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
  interval: 60m
  dependsOn:
    - name: linkerd-control-plane
