apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-v3
spec:
  releaseName: traefik
  chart:
    spec:
      # NAME                    CHART VERSION   APP VERSION     DESCRIPTION
      # traefik/traefik         28.0.0          v3.0.0          A Traefik based Kubernetes ingress controller
      chart: traefik
      version: "28.3.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 60m
