apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-agent
  namespace: monitoring
spec:
  releaseName: grafana-agent
  chart:
    spec:
      chart: grafana-agent
      version: "0.36.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 60m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-agent-operator
  namespace: monitoring
spec:
  releaseName: grafana-agent-operator
  chart:
    spec:
      chart: grafana-agent-operator
      version: "0.3.18"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 60m
