apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vmoperator
  namespace: monitoring
spec:
  releaseName: vmoperator
  chart:
    spec:
      chart: victoria-metrics-operator
      version: "0.29.3"
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
  interval: 60m
  values:
    replicaCount: 1
    resources:
      limits:
        cpu: 120m
        memory: 320Mi
      requests:
        cpu: 120m
        memory: 320Mi
