apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
spec:
  releaseName: promtail
  chart:
    spec:
      chart: promtail
      version: "6.15.5"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 60m
#  values:
#    namespace: change-me
#    podAnnotations:
#      linkerd.io/inject: enabled
#    # this needs to be overwritten
#    config:
#      clients:
#        - url: http://change-me/loki/api/v1/push
#          tenant_id: 1
#          external_labels:
#            cluster: guardian
#          basic_auth:
#            # The username to use for basic auth
#              username: "change-me"
#              password: "change-me"
#
